# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deta_mb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdeta_mb.proto\x12\x06\x64\x65tamb\"Q\n\x03Msg\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x17\n\x0flog_subs_msg_id\x18\x05 \x01(\t\",\n\x0bRespPulling\x12\x1d\n\x08messages\x18\x01 \x03(\x0b\x32\x0b.detamb.Msg\"B\n\x04Resp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"X\n\x03Req\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05\x61\x63ked\x18\x02 \x01(\x05\x12\x10\n\x08timefrom\x18\x03 \x01(\x03\x12\x0e\n\x06timeto\x18\x04 \x01(\x03\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deta_mb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSG._serialized_start=25
  _MSG._serialized_end=106
  _RESPPULLING._serialized_start=108
  _RESPPULLING._serialized_end=152
  _RESP._serialized_start=154
  _RESP._serialized_end=220
  _REQ._serialized_start=222
  _REQ._serialized_end=310
# @@protoc_insertion_point(module_scope)
